### PR TITLE
Better way of calling sys.nframe()

### LINKED ISSUE #22: GC events can cause Error: unimplemented type 'integer' in 'coerceToInteger'
For example:

```R
R
library(later)

f <- function() {
  for (j in 1:3) {
    later(function() {
      cat(".\n")
    })
  }
  gctorture(T)
}

f()
```

When I run this I get:

```
> f()
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
> Error: unimplemented type 'integer' in 'coerceToInteger'
In addition: Warning message:
An unusual circumstance has arisen in the nesting of readline input. Please report using bug.report() 
> Error: unimplemented type 'integer' in 'coerceToInteger'
In addition: Warning message:
An unusual circumstance has arisen in the nesting of readline input. Please report using bug.report() 
> Error: unimplemented type 'integer' in 'coerceToInteger'
In addition: Warning message:
An unusual circumstance has arisen in the nesting of readline input. Please report using bug.report() 
> Error: unimplemented type 'integer' in 'coerceToInteger'
In addition: Warning message:
An unusual circumstance has arisen in the nesting of readline input. Please report using bug.report() 
> .
.
.
```

### PR DESCRIPTION
**Pull request by wch**
This fixes #22.

### CODE REVIEW

File: src/later.cpp [hunk 1]
```diff
@@ -27,21 +23,30 @@ class ProtectCallbacks {
...
+// base::sys.nframe().
+int sys_nframe() {
+  SEXP e, result;
+  int errorOccurred;
+
+  PROTECT(e = Rf_lang1(Rf_install("sys.nframe")));
+  result = R_tryEval(e, R_BaseEnv, &errorOccurred);
+
+  if (errorOccurred) {
+    UNPROTECT(1);
```
Comment (jcheng5) [inline src/later.cpp]: When doing C-style manual resource management (i.e. without destructors) I think it's customary to try to have a single point of return for the function, so the cleanup code is in one place.

**Comment by jcheng5** [comment]
So much better!

File: src/later.cpp [hunk 2]
```diff
@@ -46,7 +46,12 @@ int sys_nframe() {
 bool at_top_level() {
   if (exec_callbacks_reentrancy_count != 0)
     return false;
-  return sys_nframe() == 0;
+
+  int nframe = sys_nframe();
+  if (nframe == -1) {
+    throw Rcpp::exception("Error occurred while calling sys.nframe()");
```
Comment (jcheng5) [inline src/later.cpp]: Could also make a case for returning false here. Though I guess it's a good idea at least for now, so we can see if it ever happens.
