### PR TITLE
Fix C11 threads.h compatibility

### LINKED ISSUE #45: Alpine: Package fails to load with 'Mutex creation failed' error
Hello,

I've tried building later in Alpine 3.7 and the testing stage fails with:

```
** testing if installed package can be loaded
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
Aborted (core dumped)
ERROR: loading failed
```

This can be reproduced with:

```
$ sudo docker pull alpine:3.7
$ sudo docker run --rm -it alpine:3.7
# apk add --no-cache R R-dev build-base
# R
> install.packages('later')
```

I'm installing this as it's a dependency for a shiny application which in turns depends on `pool` which I'm trying to run in Docker. Alpine uses https://www.musl-libc.org instead of the glibc commonly found in other Linux distributions.

I've also tried `master` with `remotes::install_github("r-lib/later")` and it has the same issue.

### LINKED ISSUE #63: Unable to compile on linux, "Mutex creation failed"
I can't compile later on my linux (Arch Linux), which breaks some dependencies for me. I get this error (both from github and CRAN): 

``
** testing if installed package can be loaded
sh: riga 1:  5012 Annullato               (core dump creato) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/Rtmp8kWDUc/file136713a0f686'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
ERROR: loading failed
* removing ‘/usr/lib/R/library/later’
``
This is my sessioninfo:

`R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=it_IT.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=it_IT.UTF-8        LC_COLLATE=it_IT.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=it_IT.UTF-8   
 [7] LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1  R6_2.2.2        htmltools_0.3.6 tools_3.5.1    
[5] Rcpp_0.12.18    remotes_1.1.1   digest_0.6.15   fortunes_1.5-4 
`

### PR DESCRIPTION
**Pull request by wch**
This fixes #45 and fixes #63.

Still needs some work and documentation, but hopefully it will install on platforms with glibc 2.28 (Arch) and musl (Alpine).

### CODE REVIEW

**Comment by znmeb** [comment]
Let me know when this is ready to test - Twitter @znmeb works ;-)

File: src/tinycthread/tinycthread.h [hunk 1]
```diff
@@ -28,15 +29,6 @@ freely, subject to the following restrictions:
 extern "C" {
 #endif
 
-// jcheng 2017-11-03: _XOPEN_SOURCE 600 is necessary to prevent Solaris headers
-// from complaining about the combination of C99 and _XOPEN_SOURCE <= 500. The
-// error message starts with:
-// "Compiler or options invalid for pre-UNIX 03 X/Open applications"
```
Comment (jcheng5) [inline src/tinycthread/tinycthread.h]: Is it OK that we're losing this?

File: src/c11threads.h [hunk 2]
```diff
@@ -0,0 +1,14 @@
+#ifndef _C11_THREADS_H_
+#define _C11_THREADS_H_
+
+
+/* If there's C11 <threads.h> support, use it; otherwise use tinycthread.h,
+ * which has a compatible API. */
+#ifdef THREADS_H_SUPPORT
```
Comment (jcheng5) [inline src/c11threads.h]: I think I'd rather see this require `THREADS_H_SUPPORT` to be defined one way or another, so we know that the build environment made a conscious choice rather than not knowing this issue exists. (For example, Makevars.win doesn't deal with this yet, but it would happily compile anyway...)

**Comment by wch** [comment]
@loqs Thanks! Although it happens to work, I think it's still not quite right. When I run it, the output is:

```
* installing *source* package 'later' ...
** libs
+ echo '#include <threads.h>
int main() {
    mtx_t mutex;
    mtx_init(&mutex, mtx_plain);
    return 0;
}'
+ cc -pthread -x c - -o /dev/null
+ '[' 0 -eq 0 ']'
+ echo 1
....
```

The problem is that `$(CC)` (and others) are resolving too early. It should be `gcc`, not `cc`, and there are a bunch of other compiler flags that should be there as well.

The next thing I tried is to change `:=` to `=`. When I did this, the script ran twice: once at the beginning where it looks just like what I showed above, and once at the end, where it looks like this:

```
...
+ echo '#include <threads.h>
int main() {
    mtx_t mutex;
    mtx_init(&mutex, mtx_plain);
    return 0;
}'
+ gcc -D_FORTIFY_SOURCE=2 -DTHREADS_H_SUPPORT -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -O0 -Wall -pthread -x c - -o /dev/null
+ '[' 0 -eq 0 ']'
+ echo 1
echo THREADS_H_SUPPORT is 1
THREADS_H_SUPPORT is 1
...
```

This time, it gets the correct `CC`, `PKG_CFLAGS`, and all that. However, it's running too late -- this happens after all the .o objects have already been built. The first run is triggered by the `ifeq()`. Ideally the `ifeq()` would happen after `CC` and other variables have been assigned, but that doesn't seem to be the case.

I think it is possible to hack the Makevars so that things will happen in the right order, but everything I'm finding looks pretty messy. It might be better to use a top-level configure script, similar to the one here: https://github.com/jeroen/openssl/blob/master/configure

File: src/tinycthread/tinycthread.h (hunk 1 above)
Comment (wch) [reply src/tinycthread/tinycthread.h]: I think we want to keep this and maybe a few other things -- I haven't yet reviewed the changes we made to tinycthread that we may want to preserve in the new version.

**Comment by deluciaatgfz** [comment]
The fix-c-thread branch as it is now works for me on Arch! Thanks.
