### PR TITLE
Use tinycthread on all platforms

### LINKED ISSUE #77: Load error on Fedora 29: Mutex creation failed
This is a followup to #63.

A Dockerfile that installs Anaconda and R on Fedora 29:

```R
FROM fedora:latest

RUN dnf install -y 'dnf-command(builddep)'
RUN dnf install -y wget bzip2

RUN wget https://repo.continuum.io/archive/Anaconda3-5.2.0-Linux-x86_64.sh
RUN bash ./Anaconda3-5.2.0-Linux-x86_64.sh -b
ENV PATH /root/anaconda3/bin:$PATH
RUN conda install r-base=3.5.1 r-essentials

CMD /bin/bash
```

To build the image and run the container, enter the directory with the Dockerfile and run:

```bash
docker build -t fr .
docker run --rm -ti fr /bin/bash
```

Inside the container, run:

```
R
options(repos=c(CRAN="https://cloud.r-project.org/"))
install.packages("later")
```

Some of the output:

```
> install.packages("later")
trying URL 'https://cloud.r-project.org/src/contrib/later_0.7.5.tar.gz'
Content type 'application/x-gzip' length 38900 bytes (37 KB)
==================================================
downloaded 37 KB

* installing *source* package ‘later’ ...
** package ‘later’ successfully unpacked and MD5 sums checked
Running configure script
Using CC=x86_64-conda_cos6-linux-gnu-cc
Using CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/root/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix
Using CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/root/anaconda3/include -Wl,-rpath-link,/root/anaconda3/lib
C11-style threads.h support not detected. Using tinycthread library.
...
...
...
x86_64-conda_cos6-linux-gnu-c++ -shared -L/root/anaconda3/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,-rpath,/root/anaconda3/lib -L/root/anaconda3/lib -Wl,-rpath-link,/root/anaconda3/lib -o later.so RcppExports.o callback_registry.o init.o later.o later_native.o later_posix.o later_win32.o timer_posix.o timestamp_unix.o timestamp_win32.o -pthread ./tinycthread/tinycthread.o -L/root/anaconda3/lib/R/lib -lR
installing to /root/anaconda3/lib/R/library/later/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
sh: line 1:   387 Aborted                 (core dumped) '/root/anaconda3/lib/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpkPZJXx/file10cd09078'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
ERROR: loading failed
* removing ‘/root/anaconda3/lib/R/library/later’
* restoring previous ‘/root/anaconda3/lib/R/library/later’

The downloaded source packages are in
	‘/tmp/RtmpSEDqty/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("later") :
  installation of package ‘later’ had non-zero exit status
```

### PR DESCRIPTION
**Pull request by wch**
Fixes #77. This PR makes it so later stops trying to use C11-style threads.

It changes the function names in tinycthread so that they don't conflict with (and inadverantly link to) functions with the same name from C11-style threads.

Installation can be tested by building the Fedora 29-Anaconda Docker image as described in #77, then running the following:

```
docker run --rm -ti fr /bin/bash
yum install -y unzip
wget https://github.com/r-lib/later/archive/remove-tinycthread.zip
unzip remove-tinycthread.zip
R CMD build --no-build-vignettes later-remove-tinycthread
R CMD INSTALL later_0.7.5.9001.tar.gz
```

For some reason, `R CMD check` doesn't work, but I think it's because there's some missing system dependencies.

```
[root@f07d3a24fdad /]# R CMD check later_0.7.5.9001.tar.gz 
Error in system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE) : 
  error in running command
Execution halted
```

### CODE REVIEW

File: src/badthreads.h [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+ * If any of these symbols are used in a file that includes badthreads.h, it
+ * should throw an error at compile time.
+ *
+ * The purpose of this file is to make sure that code does not accidentally
+ * use symbols from threads.h. If this happens, and the system C library has
+ * C11-style thread support, then the resulting object could link to the
+ * system's functions that have the same name, instead of the local functions.
+*/
+
+#define thrd_t              THREADS_H_ERROR
```
Comment (QuLogic) [inline src/badthreads.h]: This name (`thrd_t`) still exists even though it's listed here as bad. Pretty sure that means that `THREADS_H_ERROR` becomes the name of the type, which does mean the wrong type name is avoided, but I'm not sure that's what was intended.

**Comment by QuLogic** [comment]
On a related note, names ending in `_t` are [reserved for future type names](https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html) and should not be used. Technically, tinycthread was in violation of this already...
